#!/usr/bin/ansible-playbook
---
- name: bastion initial locally
  hosts: localhost
  connection: local
  gather_facts: yes
  remote_user: root
  tasks:
    - name: get ec2 metadata
      ec2_metadata_facts:
    - name: lookup ssm parameter store in the current region
      copy:
        content: "{{ lookup('aws_ssm', '/keypairs/ansible/private', region=vars['ansible_ec2_placement_region'], decrypt=True ) }}"
        dest: /home/ubuntu/.ssh/id_rsa
        owner: ubuntu
        group: ubuntu
        mode: 0600
