#!/usr/bin/ansible-playbook
---
- name: wordpress initial locally
  hosts: localhost
  connection: local
  gather_facts: yes
  remote_user: ubuntu
  become: yes
  become_user: root
  roles:
    - ../roles/common
    - ../roles/wordpress
