#!/usr/bin/ansible-playbook
---
- name: Wordpress bootstrap
  hosts: tag_AA_SERVER_GROUP_Wordpress
  gather_facts: yes
  remote_user: ubuntu
  become: yes
  become_user: root
  roles:
    - ../roles/common
    - ../roles/wordpress
